# fly.toml app configuration file generated for fly-sqlite-node on 2024-01-28T14:12:01+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fly-sqlite-node'
primary_region = 'ams'

[mounts]
  source = "data"
  destination = "/data"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
